networks:
  intranet:
  prometheus:
  grafana:
  k6:
  influxdb:

volumes:
  sqlite:

services:
  gateway:
    image: petal-hub/gateway:v0.1.0
    build:
      context: ./gateway
    command: ["serve", "-dsn", "/var/lib/sqlite/todos.db"]
    ports:
      - "8080:8080"
    networks:
      - intranet
      - k6
    volumes:
      - sqlite:/var/lib/sqlite
    depends_on:
      - sqlite-migrate

  sqlite-migrate:
    image: petal-hub/gateway:v0.1.0
    build:
      context: ./gateway
    command: ["migrate", "-dsn", "/var/lib/sqlite/todos.db"]
    volumes:
      - sqlite:/var/lib/sqlite

  prometheus:
    image: prom/prometheus:v2.51.1
    command: ["--config.file", "/etc/prometheus/prometheus.yml"]
    ports:
      - "9090:9090"
    networks:
      - prometheus
      - grafana

  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0

  grafana:
    image: grafana/grafana:10.2.6
    networks:
      - grafana
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  k6:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - K6_INFLUXDB_PUSH_INTERVAL=1s
    volumes:
      - ./k6/src:/src
