global:
  scrape_interval: "15s"
  # scrape_timeout: "10s"
  # evaluation_interval:

scrape_configs:
  - job_name: petal_hub_gateway
    static_configs:
      - targets:
          - "gateway:8080"
    # metrics_path: /metrics
    # honor_labels: false
    # honor_timestamps: true
    # scheme: http
    # follow_redirects: true
    # body_size_limit: 0
    # sample_limit: 0
    # label_limit: 0
    # label_name_length_limit: 0
    # label_value_length_limit: 0
    # target_limit: 0
